### ISSUE TITLE
Plan and execute a load test with 500 devices

### ISSUE THREAD

**Issue by coderbyheart** [hello-nrfcloud/backend#175]

**Comment by pudkrong** [comment]
Do you want to create load test which will fire requests to nRF Cloud server or just to our MQTT bridge server? The scenarios will be similar to the simulator device. The current simulator device cli performs the followings

### Once
- Location

### Every 10 seconds
- Battery
- Gain

### Every 1 minute
- Update device info

**Comment by coderbyheart** [comment]
We need to load test our implementation only, we can assume that nRF Cloud is able to handle this.

**Comment by coderbyheart** [comment]
Please add test plan and metrics here.

**Comment by pudkrong** [comment]
# Load Test Results

## Test Objective

Our goal for this load test was to sustain 500 concurrent devices along with
WebSocket connection within 30 minutes. Each device was expected to publish
solar and battery data every 10 seconds and a ground fix location once.

## Backend Configuration: hello.nrfcloud

- Shadow fetching configuration set to 10 seconds.

## Expected Results

- Device identity messages were published 500 times.
- Solar data was published 90,000 times.
- Battery data was published 90,000 times.
- Shadow data was published more than 90,000 times.
  - Shadow data fetched every 10 seconds.
  - Shadow messages published during warm-up and cool-down periods.
- 500 WebSocket connections were created and closed at the end.
- MQTT bridge's CPU and memory utilization remained under 50%.
- Lambda success rate exceeded 90%.

## Test Outcome

### Artillery Load Test Summary

```
--------------------------------
Summary report @ 09:22:35(+0000)
--------------------------------

mqtt.close: .................................................................... 500
mqtt.connect: .................................................................. 500
mqtt.connect_rate: ............................................................. 0/sec
mqtt.publish_count: ............................................................ 180500
mqtt.publish_rate: ............................................................. 91/sec
vusers.completed: .............................................................. 500
vusers.created: ................................................................ 500
vusers.created_by_name.IoT simulator devices: .................................. 500
vusers.failed: ................................................................. 0
vusers.session_length:
  min: ......................................................................... 1800107.7
  max: ......................................................................... 1800340.5
  median: ...................................................................... 1812885.5
  p95: ......................................................................... 1812885.5
  p99: ......................................................................... 1812885.5
ws.connect: .................................................................... 500
ws.context.battery: ............................................................ 89383
ws.context.deviceIdentity: ..................................................... 499
ws.context.gain: ............................................................... 89381
ws.context.reported: ........................................................... 128427
ws.disconnect: ................................................................. 500
ws.receive_rate.battery: ....................................................... 45/sec
ws.receive_rate.deviceIdentity: ................................................ 0/sec
ws.receive_rate.gain: .......................................................... 45/sec
ws.receive_rate.reported: ...................................................... 66/sec
```

[Load test report](https://github.com/hello-nrfcloud/backend/files/12536247/result.json.html.zip)

### AWS CloudWatch Metrics

![image](https://github.com/hello-nrfcloud/backend/assets/2525169/c7c31da5-8abd-464d-a50e-bfb175feea28)

## Conclusion

### 1. Device Identity Messages (Expected: 500)

- Received: 499 device identity messages
- Success Rate: 99.8%

### 2. Solar Data Messages (Expected: 90,000)

- Received: 89,381 gain messages
- Success Rate: 99.31%

### 3. Battery Data Messages (Expected: 90,000)

- Received: 89,383 battery messages
- Success Rate: 99.31%

### 4. Shadow Data Messages (Expected: >90,000)

- Received: 128,427 shadow messages
- Success Rate: 142.7%
- The surplus shadow messages were received during warm-up and cool-down periods

### 5. WebSocket Connections (Expected: 500)

- 500 WebSocket connections were established at the beginning.
- 500 WebSocket connections were disconnected at the end.

### 6. MQTT Bridge Utilization

- CPU utilization: Less than 5%
- Memory utilization: Less than 1%

### 7. Lambda Success Rate (Expected: >90%)

- Lambda success rate: 100%
